# Generated by Django 3.0.1 on 2020-01-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='Location_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'location_cities',
            },
        ),
        migrations.CreateModel(
            name='Location_road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'location_roads',
            },
        ),
        migrations.CreateModel(
            name='Location_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Location_city')),
            ],
            options={
                'db_table': 'location_states',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location_detail', models.CharField(max_length=300)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Food')),
                ('location_do', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Location_city')),
                ('location_dong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Location_road')),
                ('location_gu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Location_state')),
                ('price_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Price')),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.AddField(
            model_name='location_road',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Location_state'),
        ),
    ]
