# Generated by Django 3.0.1 on 2020-01-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Top_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'top_lists',
            },
        ),
        migrations.CreateModel(
            name='Top_lists_Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant')),
                ('top_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Top_List')),
            ],
            options={
                'db_table': 'top_lists_restaurants',
            },
        ),
        migrations.CreateModel(
            name='Restaurant_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Tag')),
            ],
            options={
                'db_table': 'restaurants_tags',
            },
        ),
        migrations.CreateModel(
            name='Restaurant_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=20)),
                ('last_order', models.CharField(max_length=45)),
                ('info', models.CharField(max_length=300)),
                ('site', models.URLField(max_length=2500)),
                ('breaktime', models.DateTimeField()),
                ('opening_horus', models.DateTimeField()),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant')),
            ],
            options={
                'db_table': 'restaurants_info',
            },
        ),
        migrations.CreateModel(
            name='Restaurant_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.URLField(max_length=2500)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant')),
            ],
            options={
                'db_table': 'restaurant_images',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=200)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Eat_Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('discount_rate', models.IntegerField()),
                ('menu', models.CharField(max_length=300)),
                ('menu_info', models.CharField(max_length=1000)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant')),
            ],
            options={
                'db_table': 'eat_deals',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Restaurants_top_lists',
            field=models.ManyToManyField(through='restaurant.Top_lists_Restaurant', to='restaurant.Top_List'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='holiday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Holiday'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags_restaurants',
            field=models.ManyToManyField(through='restaurant.Restaurant_Tag', to='restaurant.Tag'),
        ),
    ]
