# Generated by Django 3.0.1 on 2020-01-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200108_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location_do',
            new_name='location_city',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='location_dong',
            new_name='location_road',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='location_gu',
            new_name='location_state',
        ),
    ]
