# Generated by Django 3.0.1 on 2020-01-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200108_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Restaurants_top_lists',
            new_name='restaurants_top_lists',
        ),
    ]
