# Generated by Django 3.0.1 on 2020-01-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200108_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
