# Generated by Django 3.0.1 on 2020-01-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20200109_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat_deal',
            name='restaurant_intro',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
