# Generated by Django 3.0.1 on 2020-01-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_eat_deal_restaurant_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat_deal',
            name='restaurant_intro',
            field=models.CharField(max_length=300),
        ),
    ]
