# Generated by Django 3.0.1 on 2020-01-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20200109_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_lists_restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='top_list',
            name='image',
            field=models.URLField(max_length=2500, null=True),
        ),
    ]
