# Generated by Django 3.0.1 on 2020-01-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20200109_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_info',
            old_name='opening_horus',
            new_name='opening_hours',
        ),
        migrations.AlterField(
            model_name='top_list',
            name='image',
            field=models.URLField(max_length=2500),
        ),
    ]
