# Generated by Django 3.0.1 on 2020-01-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20200109_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_info',
            name='breaktime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_info',
            name='info',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_info',
            name='opening_hours',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
