# Generated by Django 3.0.1 on 2020-01-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reveiw_start',
            new_name='reveiw_star',
        ),
    ]
