# Generated by Django 3.0.1 on 2020-01-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200108_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reveiw_star',
            new_name='review_star',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
