# Generated by Django 3.0.1 on 2020-01-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200108_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_image',
            name='image',
            field=models.URLField(max_length=4500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
