# Generated by Django 3.0.1 on 2020-01-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200110_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_star',
            name='content',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
